#!/bin/bash

# For apps that expect debian's 'x-terminal-emulator'

# Adding this to the PATH could help with
# detecting the default terminal emulator

if [[ -n "$TERMINAL" ]]; then
	$TERMINAL
else
	exit 1
fi
